#
# Marlin Firmware
# PlatformIO Configuration File
#

#################################
#                               #
#      ESP32 Architecture       #
#                               #
#################################

#
# Espressif ESP32
#
[env:esp32]
platform         = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip
platform_packages = espressif/toolchain-xtensa-esp32s3
board             = esp32dev
build_flags       = ${common.build_flags} -DCORE_DEBUG_LEVEL=0 -Wno-volatile
build_src_filter  = ${common.default_src_filter} +<src/HAL/ESP32>
lib_ignore        = NativeEthernet, AsyncTCP_RP2040W
upload_speed      = 115200
monitor_speed     = 115200
monitor_filters   = colorize, time, send_on_enter, log2file, esp32_exception_decoder
monitor_echo = yes
#upload_port      = marlinesp.local
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L

[env:FYSETC_E4]
extends                = env:esp32
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

[env:PANDA]
extends                = env:esp32
build_flags            = ${env:esp32.build_flags} -DUSE_ESP32_EXIO 
lib_deps               = ${common.lib_deps}
                         SoftwareSerialEsp32
board_build.partitions = Marlin/src/HAL/ESP32/esp32.csv

[env:mks_tinybee]
extends                = env:esp32
board_build.partitions = default_8MB.csv
board_upload.flash_size = 8MB

[env:godi_esp32]
extends                = env:esp32
board_build.partitions = Marlin/src/HAL/ESP32/esp32.csv
